---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx1
  labels:
    web : subdomain1-dep
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app1: subdomain1
  template:
    metadata:
      labels:
        app1: subdomain1
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mynginx2
  labels:
    web : subdomain2-dep
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app2: subdomain2
  template:
    metadata:
      labels:
        app2: subdomain2
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
