---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mynginx1-hpa

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mynginx1
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage:  {{ .Values.autoscaling.CpuPercentage }}
  
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mynginx2-hpa

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mynginx2
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage:  {{ .Values.autoscaling.CpuPercentage }}
