apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mynginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.address1 }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: subdomain1
                port:
                  number: {{ .Values.service.port }}
    - host: {{ .Values.address2 }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: subdomain2
                port:
                  number: {{ .Values.service.port }}
