---
apiVersion: v1
kind: Service
metadata:
  name: subdomain1

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http  # Referring name of the containerPort:80
      protocol: TCP
      name: http
  selector:
     app1: subdomain1

---
apiVersion: v1
kind: Service
metadata:
  name: subdomain2

spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http  # Referring name of the containerPort:80
      protocol: TCP
      name: http
  selector:
     app2: subdomain2
